name: SSH into macOS via tmate

on:
  push:
    branches:
      - main

jobs:
  remote-ssh:
    runs-on: macos-latest  # Or any runner type you need (e.g., macOS)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      

    - name: Install tmate
    uses: mxschmitt/action-tmate@v2
