name: Install and Run AnyDesk Server on macOS

on:
  push:
    branches:
      - main

jobs:
  install_anydesk:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: |
          # Install Homebrew if it's not already installed
          if ! command -v brew &> /dev/null; then
            echo "Homebrew not found, installing..."
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          else
            echo "Homebrew already installed"
          fi

      - name: Install AnyDesk via Homebrew
        run: |
          # Install AnyDesk using Homebrew
          brew install --cask anydesk || { echo 'AnyDesk installation failed!'; exit 1; }

      - name: Launch AnyDesk Server
        run: |
          # Launch AnyDesk in the background
          open -g -a "/Applications/AnyDesk.app" || { echo 'Failed to open AnyDesk!'; exit 1; }
          sleep 30  # Give it time to initialize

      - name: Search for AnyDesk ID and Password
        run: |
          echo "Searching for AnyDesk ID and Password..."

          CONFIG_PATHS=(
            "$HOME/Library/Application Support/AnyDesk"
            "/Library/Application Support/AnyDesk"
          )

          FOUND=0
          for path in "${CONFIG_PATHS[@]}"; do
            if [ -d "$path" ]; then
              echo "Searching in: $path"
              ID_FILE="$path/id.txt"
              if [ -f "$ID_FILE" ]; then
                ID=$(cat "$ID_FILE")
                echo "Found AnyDesk ID: $ID"
                FOUND=1
              else
                echo "ID file not found."
              fi
              break
            fi
          done

          if [ $FOUND -eq 0 ]; then
            echo "Could not find AnyDesk ID."
          fi

      - name: Keep Alive
        run: |
          # Keep the job running
          tail -f /dev/null
