name: Install and Run RustDesk Server on macOS

on:
  push:
    branches:
      - main

jobs:
  install_rustdesk:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download RustDesk macOS version
        run: |
          brew install rustdesk

      - name: Launch RustDesk Server
        run: |
          open -g -a "/Applications/RustDesk.app"
          sleep 10  # Give it time to initialize

      - name: Retrieve ID and Password
        run: |
          CONFIG_FILE="$HOME/Library/Preferences/com.rustdesk.server.plist"
          if [ -f "$CONFIG_FILE" ]; then
            ID=$(defaults read "$CONFIG_FILE" "ID" 2>/dev/null || echo "Not found")
            PASSWORD=$(defaults read "$CONFIG_FILE" "Password" 2>/dev/null || echo "Not found")
            echo "RustDesk Server ID: $ID"
            echo "RustDesk Server Password: $PASSWORD"
          else
            echo "Configuration file not found. Could not retrieve ID and password."
          fi

      - name: Keep Alive
        run: tail -f /dev/null
