name: Install and Run LiteManager Server on macOS

on:
  push:
    branches:
      - main

jobs:
  install_litemanager:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download LiteManager.dmg
        run: |
          curl -L -A "Mozilla/5.0" -o LiteManager.dmg https://litemanager.com/download/LiteManager.dmg
          file LiteManager.dmg
          if [[ $(file LiteManager.dmg) != *"Apple Disk Image"* ]]; then
            echo "Download failed or not a valid DMG. Aborting."
            exit 1
          fi

      - name: Mount DMG
        run: |
          hdiutil attach LiteManager.dmg

      - name: Install LiteManager
        run: |
          sudo cp -R /Volumes/LiteManager*/LiteManager.app /Applications/
          hdiutil detach /Volumes/LiteManager*

      - name: Launch LiteManager Server
        run: |
          open -g -a "/Applications/LiteManager.app"
          sleep 10  # Give it time to initialize

      - name: Retrieve ID and Password
        run: |
          CONFIG_FILE="$HOME/Library/Preferences/com.litemanager.server.plist"
          if [ -f "$CONFIG_FILE" ]; then
            ID=$(defaults read "$CONFIG_FILE" "ID" 2>/dev/null || echo "Not found")
            PASSWORD=$(defaults read "$CONFIG_FILE" "Password" 2>/dev/null || echo "Not found")
            echo "LiteManager Server ID: $ID"
            echo "LiteManager Server Password: $PASSWORD"
          else
            echo "Configuration file not found. Could not retrieve ID and password."
          fi

      - name: Keep Alive
        run: tail -f /dev/null
